/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VoiceRouteImport } from './routes/voice'
import { Route as TypographyRouteImport } from './routes/typography'
import { Route as StockPhotosRouteImport } from './routes/stock-photos'
import { Route as StockDownloadsRouteImport } from './routes/stock-downloads'
import { Route as SocialRouteImport } from './routes/social'
import { Route as SearchRouteImport } from './routes/search'
import { Route as PromptsRouteImport } from './routes/prompts'
import { Route as LogoLibraryRouteImport } from './routes/logo-library'
import { Route as LogoRouteImport } from './routes/logo'
import { Route as LeadFormsRouteImport } from './routes/lead-forms'
import { Route as EmailSignatureRouteImport } from './routes/email-signature'
import { Route as DownloadsRouteImport } from './routes/downloads'
import { Route as ColorRouteImport } from './routes/color'
import { Route as BusinessCardRouteImport } from './routes/business-card'
import { Route as ApplicationsRouteImport } from './routes/applications'
import { Route as AccessibilityRouteImport } from './routes/accessibility'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SocialIndexRouteImport } from './routes/social.index'
import { Route as SocialFathersDayRouteImport } from './routes/social.fathers-day'
import { Route as SocialPlatformRouteImport } from './routes/social.$platform'

const VoiceRoute = VoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => rootRouteImport,
} as any)
const TypographyRoute = TypographyRouteImport.update({
  id: '/typography',
  path: '/typography',
  getParentRoute: () => rootRouteImport,
} as any)
const StockPhotosRoute = StockPhotosRouteImport.update({
  id: '/stock-photos',
  path: '/stock-photos',
  getParentRoute: () => rootRouteImport,
} as any)
const StockDownloadsRoute = StockDownloadsRouteImport.update({
  id: '/stock-downloads',
  path: '/stock-downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialRoute = SocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptsRoute = PromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoLibraryRoute = LogoLibraryRouteImport.update({
  id: '/logo-library',
  path: '/logo-library',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoRoute = LogoRouteImport.update({
  id: '/logo',
  path: '/logo',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadFormsRoute = LeadFormsRouteImport.update({
  id: '/lead-forms',
  path: '/lead-forms',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailSignatureRoute = EmailSignatureRouteImport.update({
  id: '/email-signature',
  path: '/email-signature',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsRoute = DownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const ColorRoute = ColorRouteImport.update({
  id: '/color',
  path: '/color',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessCardRoute = BusinessCardRouteImport.update({
  id: '/business-card',
  path: '/business-card',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsRoute = ApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityRoute = AccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialIndexRoute = SocialIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SocialRoute,
} as any)
const SocialFathersDayRoute = SocialFathersDayRouteImport.update({
  id: '/fathers-day',
  path: '/fathers-day',
  getParentRoute: () => SocialRoute,
} as any)
const SocialPlatformRoute = SocialPlatformRouteImport.update({
  id: '/$platform',
  path: '/$platform',
  getParentRoute: () => SocialRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accessibility': typeof AccessibilityRoute
  '/applications': typeof ApplicationsRoute
  '/business-card': typeof BusinessCardRoute
  '/color': typeof ColorRoute
  '/downloads': typeof DownloadsRoute
  '/email-signature': typeof EmailSignatureRoute
  '/lead-forms': typeof LeadFormsRoute
  '/logo': typeof LogoRoute
  '/logo-library': typeof LogoLibraryRoute
  '/prompts': typeof PromptsRoute
  '/search': typeof SearchRoute
  '/social': typeof SocialRouteWithChildren
  '/stock-downloads': typeof StockDownloadsRoute
  '/stock-photos': typeof StockPhotosRoute
  '/typography': typeof TypographyRoute
  '/voice': typeof VoiceRoute
  '/social/$platform': typeof SocialPlatformRoute
  '/social/fathers-day': typeof SocialFathersDayRoute
  '/social/': typeof SocialIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accessibility': typeof AccessibilityRoute
  '/applications': typeof ApplicationsRoute
  '/business-card': typeof BusinessCardRoute
  '/color': typeof ColorRoute
  '/downloads': typeof DownloadsRoute
  '/email-signature': typeof EmailSignatureRoute
  '/lead-forms': typeof LeadFormsRoute
  '/logo': typeof LogoRoute
  '/logo-library': typeof LogoLibraryRoute
  '/prompts': typeof PromptsRoute
  '/search': typeof SearchRoute
  '/stock-downloads': typeof StockDownloadsRoute
  '/stock-photos': typeof StockPhotosRoute
  '/typography': typeof TypographyRoute
  '/voice': typeof VoiceRoute
  '/social/$platform': typeof SocialPlatformRoute
  '/social/fathers-day': typeof SocialFathersDayRoute
  '/social': typeof SocialIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accessibility': typeof AccessibilityRoute
  '/applications': typeof ApplicationsRoute
  '/business-card': typeof BusinessCardRoute
  '/color': typeof ColorRoute
  '/downloads': typeof DownloadsRoute
  '/email-signature': typeof EmailSignatureRoute
  '/lead-forms': typeof LeadFormsRoute
  '/logo': typeof LogoRoute
  '/logo-library': typeof LogoLibraryRoute
  '/prompts': typeof PromptsRoute
  '/search': typeof SearchRoute
  '/social': typeof SocialRouteWithChildren
  '/stock-downloads': typeof StockDownloadsRoute
  '/stock-photos': typeof StockPhotosRoute
  '/typography': typeof TypographyRoute
  '/voice': typeof VoiceRoute
  '/social/$platform': typeof SocialPlatformRoute
  '/social/fathers-day': typeof SocialFathersDayRoute
  '/social/': typeof SocialIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accessibility'
    | '/applications'
    | '/business-card'
    | '/color'
    | '/downloads'
    | '/email-signature'
    | '/lead-forms'
    | '/logo'
    | '/logo-library'
    | '/prompts'
    | '/search'
    | '/social'
    | '/stock-downloads'
    | '/stock-photos'
    | '/typography'
    | '/voice'
    | '/social/$platform'
    | '/social/fathers-day'
    | '/social/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accessibility'
    | '/applications'
    | '/business-card'
    | '/color'
    | '/downloads'
    | '/email-signature'
    | '/lead-forms'
    | '/logo'
    | '/logo-library'
    | '/prompts'
    | '/search'
    | '/stock-downloads'
    | '/stock-photos'
    | '/typography'
    | '/voice'
    | '/social/$platform'
    | '/social/fathers-day'
    | '/social'
  id:
    | '__root__'
    | '/'
    | '/accessibility'
    | '/applications'
    | '/business-card'
    | '/color'
    | '/downloads'
    | '/email-signature'
    | '/lead-forms'
    | '/logo'
    | '/logo-library'
    | '/prompts'
    | '/search'
    | '/social'
    | '/stock-downloads'
    | '/stock-photos'
    | '/typography'
    | '/voice'
    | '/social/$platform'
    | '/social/fathers-day'
    | '/social/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessibilityRoute: typeof AccessibilityRoute
  ApplicationsRoute: typeof ApplicationsRoute
  BusinessCardRoute: typeof BusinessCardRoute
  ColorRoute: typeof ColorRoute
  DownloadsRoute: typeof DownloadsRoute
  EmailSignatureRoute: typeof EmailSignatureRoute
  LeadFormsRoute: typeof LeadFormsRoute
  LogoRoute: typeof LogoRoute
  LogoLibraryRoute: typeof LogoLibraryRoute
  PromptsRoute: typeof PromptsRoute
  SearchRoute: typeof SearchRoute
  SocialRoute: typeof SocialRouteWithChildren
  StockDownloadsRoute: typeof StockDownloadsRoute
  StockPhotosRoute: typeof StockPhotosRoute
  TypographyRoute: typeof TypographyRoute
  VoiceRoute: typeof VoiceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/voice': {
      id: '/voice'
      path: '/voice'
      fullPath: '/voice'
      preLoaderRoute: typeof VoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/typography': {
      id: '/typography'
      path: '/typography'
      fullPath: '/typography'
      preLoaderRoute: typeof TypographyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock-photos': {
      id: '/stock-photos'
      path: '/stock-photos'
      fullPath: '/stock-photos'
      preLoaderRoute: typeof StockPhotosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock-downloads': {
      id: '/stock-downloads'
      path: '/stock-downloads'
      fullPath: '/stock-downloads'
      preLoaderRoute: typeof StockDownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social': {
      id: '/social'
      path: '/social'
      fullPath: '/social'
      preLoaderRoute: typeof SocialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompts': {
      id: '/prompts'
      path: '/prompts'
      fullPath: '/prompts'
      preLoaderRoute: typeof PromptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logo-library': {
      id: '/logo-library'
      path: '/logo-library'
      fullPath: '/logo-library'
      preLoaderRoute: typeof LogoLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logo': {
      id: '/logo'
      path: '/logo'
      fullPath: '/logo'
      preLoaderRoute: typeof LogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lead-forms': {
      id: '/lead-forms'
      path: '/lead-forms'
      fullPath: '/lead-forms'
      preLoaderRoute: typeof LeadFormsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email-signature': {
      id: '/email-signature'
      path: '/email-signature'
      fullPath: '/email-signature'
      preLoaderRoute: typeof EmailSignatureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads': {
      id: '/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof DownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/color': {
      id: '/color'
      path: '/color'
      fullPath: '/color'
      preLoaderRoute: typeof ColorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-card': {
      id: '/business-card'
      path: '/business-card'
      fullPath: '/business-card'
      preLoaderRoute: typeof BusinessCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications': {
      id: '/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof ApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility': {
      id: '/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social/': {
      id: '/social/'
      path: '/'
      fullPath: '/social/'
      preLoaderRoute: typeof SocialIndexRouteImport
      parentRoute: typeof SocialRoute
    }
    '/social/fathers-day': {
      id: '/social/fathers-day'
      path: '/fathers-day'
      fullPath: '/social/fathers-day'
      preLoaderRoute: typeof SocialFathersDayRouteImport
      parentRoute: typeof SocialRoute
    }
    '/social/$platform': {
      id: '/social/$platform'
      path: '/$platform'
      fullPath: '/social/$platform'
      preLoaderRoute: typeof SocialPlatformRouteImport
      parentRoute: typeof SocialRoute
    }
  }
}

interface SocialRouteChildren {
  SocialPlatformRoute: typeof SocialPlatformRoute
  SocialFathersDayRoute: typeof SocialFathersDayRoute
  SocialIndexRoute: typeof SocialIndexRoute
}

const SocialRouteChildren: SocialRouteChildren = {
  SocialPlatformRoute: SocialPlatformRoute,
  SocialFathersDayRoute: SocialFathersDayRoute,
  SocialIndexRoute: SocialIndexRoute,
}

const SocialRouteWithChildren =
  SocialRoute._addFileChildren(SocialRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessibilityRoute: AccessibilityRoute,
  ApplicationsRoute: ApplicationsRoute,
  BusinessCardRoute: BusinessCardRoute,
  ColorRoute: ColorRoute,
  DownloadsRoute: DownloadsRoute,
  EmailSignatureRoute: EmailSignatureRoute,
  LeadFormsRoute: LeadFormsRoute,
  LogoRoute: LogoRoute,
  LogoLibraryRoute: LogoLibraryRoute,
  PromptsRoute: PromptsRoute,
  SearchRoute: SearchRoute,
  SocialRoute: SocialRouteWithChildren,
  StockDownloadsRoute: StockDownloadsRoute,
  StockPhotosRoute: StockPhotosRoute,
  TypographyRoute: TypographyRoute,
  VoiceRoute: VoiceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
